### ISSUE TITLE
Looking for sending message from parent to iframe

### ISSUE THREAD

**Issue by apple77y** [InteractiveAdvertisingBureau/safeframe#16]
I've found the way to send message`from iframe to parent`, through using `$sf.ext.message` and `posMessageCallback`, but I cannot find a way to send a message `from parent window to iframe`.

I find one method in `host.js`, as you can see the below.

``` javascript
	/**
	 * Send a message to a child iframe.
	 *
	 * @name $sf.lib.dom.msghost.send
	 * @public
	 * @static
	 * @function
	 * @param {string} tgtID The HTML id attribute of the iframe element for which to send a message
	 * @param {string} data The string of data to send to the given iframe
	 * @returns {boolean} Whether or not message was send succesfully (note that this does not mean message was handled / recevied, only that sending was ok).
	 *
	*/

	function send_msg_to_child_iframe(tgtID, data)
```

Also, method of use (that I'm gussing)

``` javascript
$sf.lib.dom.msghost.send("leftAdPlacement", "myMessageText");
```

It looks like what I intended, but I still don't know how iframe gets message from parent.
(I'm concerning the alternative way using #9 if there's no way.)

Any help will be great.
Thx.

**Comment by seansd-zz** [comment]
you can't. . that method is not really intended for your own use, it's used from SafeFrames internally.  There is purposefully no way to allow you to receive a postmessage in a safeframe right now. . .that's an on going discussion that has to be addressed via a rewrite of the message bus that I haven't gotten around too. . .

**Comment by apple77y** [comment]
@seansd I've got it!
